insert into categories (name) values ('Arts & Photography'),
('Biographies & Memoirs'),
('Business & Investing'),
('Calendars'),
('Children''s Books'),
('Christian Books & Bibles'),
('Comics & Graphic Novels'),
('Computers & Technology'),
('Cookbooks, Food & Wine'),
('Crafts, Hobbies & Home'),
('Education & Reference'),
('Erotica'),
('Health, Fitness & Dieting'),
('History'),
('Humour & Entertainment'),
('Law'),
('LGBTQ2S+'),
('Literature & Fiction'),
('Medical Books'),
('Mystery, Thriller & Suspense'),
('Parenting & Relationships'),
('Politics & Social Sciences'),
('Professional & Technical'),
('Religion & Spirituality'),
('Romance'),
('Science & Math'),
('Science Fiction & Fantasy'),
('Self-Help'),
('Sports & Outdoors'),
('Teen & Young Adult'),
('Textbooks'),
('Travel');
