insert into favorites (user_id, book_id) values (2, 1);
insert into favorites ( user_id, book_id) values (8, 6);
insert into favorites (user_id, book_id) values (5, 5);
insert into favorites (user_id, book_id) values (9, 2);
insert into favorites (user_id, book_id) values (5, 9);
insert into favorites (user_id, book_id) values (4, 3);
insert into favorites (user_id, book_id) values (5, 6);
insert into favorites (user_id, book_id) values (8, 2);
insert into favorites (user_id, book_id) values (10, 1);
insert into favorites (user_id, book_id) values ( 1, 6);
insert into favorites (user_id, book_id) values ( 10, 3);
insert into favorites (user_id, book_id) values ( 4, 7);
insert into favorites (user_id, book_id) values ( 3, 10);
insert into favorites (user_id, book_id) values ( 8, 7);
insert into favorites (user_id, book_id) values ( 4, 10);
insert into favorites (user_id, book_id) values ( 4, 10);
insert into favorites (user_id, book_id) values ( 10, 4);
insert into favorites (user_id, book_id) values ( 4, 3);
insert into favorites (user_id, book_id) values ( 7, 9);
insert into favorites (user_id, book_id) values ( 8, 9);
