DROP TABLE IF EXISTS books CASCADE;
CREATE TABLE books (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL DEFAULT 0,
  rating SMALLINT NOT NULL DEFAULT 0,
  image VARCHAR(255) NOT NULL,
  review TEXT,
  seller_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  isFeatured BOOLEAN,
  isSold BOOLEAN
);
